### ISSUE TITLE
Usage of DoubleVar.set and get causes deadlock

### ISSUE THREAD

**Issue by actual-panda** [RedFantom/mtTkinter#11]
Example program:

    import time
    import threading
    import Tkinter as tk
    import ttk
    import mttkinter
    
    LOCK = threading.Lock()
    
    class Video(threading.Thread):
        def __init__(self):
            super(Video, self).__init__()
            self.daemon = True
            self.frame = tk.DoubleVar(root, value=0)
            self.frames = 1000
    
        def run(self):
            while True:                
                with LOCK:   
                    position = self.frame.get()
    
                    if position < self.frames:
                        position += 1
                    else:
                        position = 0
    
                    self.frame.set(position)                
    
                time.sleep(0.01)
    
    root = tk.Tk()
    video = Video()
    root.minsize(500, 50)
    
    def cb_scale(_):
        with LOCK:
            print('HELLO')
    
    scale = ttk.Scale(
        root, from_=video.frame.get(), to=video.frames, variable=video.frame,
        command=cb_scale)
    
    scale.grid(row=0, column=0, sticky=tk.EW)
    root.columnconfigure(0, weight=1)
    
    if __name__ == '__main__':
        video.start()
        root.mainloop()

Issue: spam-clicking the progress bar freezes the GUI.

Without the calls to `frame.get` and `frame.set` in the `while` loop the program does not freeze.

You can confirm that the `DoubleVar` is the culprit by using

    class DummyDoubleVar(object):
        def get(self):
            return 500
    
        def set(self, _):
            pass

and

    self.frame = DummyDoubleVar()

in `Video.__init__`. Using the `DummyDoubleVar` prevents the program from freezing.

Software used: 

Python 2.7.15  
Tkinter 8.6  
Ubuntu 18.04.3 LTS

**Comment by RedFantom** [comment]
Actually, the issue is not within `mtTkinter` here, it is within your usage of a separate lock to protect the `DoubleVar`. The following code works just fine:
```python
import time
import threading
import Tkinter as tk
import ttk
import mttkinter


class Video(threading.Thread):
    def __init__(self):
        super(Video, self).__init__()
        self.daemon = True
        self.frame = tk.DoubleVar(root, value=0)
        self.frames = 1000

    def run(self):
        while True:
            position = self.frame.get()

            if position < self.frames:
                position += 1
            else:
                position = 0

            self.frame.set(position)

            time.sleep(0.01)


root = tk.Tk()
video = Video()
root.minsize(500, 50)


def cb_scale(_):
    print('HELLO')


scale = ttk.Scale(
    root, from_=video.frame.get(), to=video.frames, variable=video.frame,
    command=cb_scale)

scale.grid(row=0, column=0, sticky=tk.EW)
root.columnconfigure(0, weight=1)

if __name__ == '__main__':
    video.start()
    root.mainloop()
```

Now, my guess would be that what is actually happening is that the moment that after the thread requests the lock, you use a `DoubleVar` call which is queued by `mtTKinter` because it is from a thread. Then the `MainThread`, which is running the `mainloop`, takes over while the `Video` is waiting, but the first `Tkinter` call to be made there is one to `cb_scale`, which then also wants the lock. Neither the `MainThread` nor the `Video` will advance, as `Video` holds the `threading.Lock`, but is waiting for the `MainThread` to execute the deferred `DoubleVar.get`. This is expected behaviour.

`mtTkinter` already makes the behaviour thread-safe, using a separate `threading.Lock` is not necessary and in this case even causes trouble. In short: Just remove the `threading.Lock` and everything should work fine.

**Comment by actual-panda** [comment]
Thanks for your speedy and competent answer!

I already knew that removing the lock would fix the demo program, but I could not wrap my head around why.

Interestingly, the GUI also freezes without `mttkinter`, so the specifics of the `mttkinter` queueing mechanism do not seem to be the issue.

Unfortunately, while not critical in the demo I posted, I cannot remove the locks in my real program. The thread is setting the frame position of an OpenCV `VideoCapture` and displaying the latest frame.

The scale can also set the frame position of the `VideoCapture` from the main thread. These two operations need to be locked, otherwise OpenCV reliably crashes the whole program.

Any idea how to proceed? Also, feel free to answer my [question](https://stackoverflow.com/questions/58590281/why-is-this-tkinter-program-freezing) over at stackoverflow if you want to.

**Comment by RedFantom** [comment]
This turns out to be quite an interesting rabbit hole. I am not sure yet what the problematic mechanism is here and my research so far has not yielded any results. Unfortunately, I do not have time to finish the research right now. I will try to take another look at it this weekend, when I hope to have more time.

**Comment by actual-panda** [comment]
There is no hurry, you are amazing for sacrificing your time for this issue at all.

I am currently working around the problem by using a regular `float` instance variable in the thread and schedule progress bar related actions via `tkinter`'s `after` method.

**Comment by RedFantom** [comment]
So, I believe I have discovered the root cause of the issue. My full explanation is available in the [StackOverflow](https://stackoverflow.com/questions/58590281/why-is-this-tkinter-program-freezing/58772436#58772436)-answer I wrote. I hope it is sufficient, if not, please let me know.

I really quite enjoyed this puzzle, thank you for sharing this issue. Still, it does not appear that any code-changes in this repository will be required. Perhaps a PR to the CPython distribution, if the changes made to `_tkinter.c` in the meantime (and the master branch of CPython does contain some, also to do with threading) haven't solved the problem already. I have not gone so far as to try. The described problem is at the very least also in the Python 3.6 source code.
